apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: backend-deploy-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: dog-facts-backend
    - name: image-repo
      value: quay.io/timothy_credo/dog-facts-backend
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/group-4-app-backend
    - name: sha
      value: 5ed54f84c35fb5734aee08f2a613a667c77d48d0
  pipelineRef:
    name: backend-deploy
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
          - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials