apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- build-bot.ServiceAccount.yaml
- create-configuration.Task.yaml
- deploy.Task.yaml
- backend-deploy.Pipeline.yaml
- quay-io-credentials.Secret.yaml
- webhook-receiver.EventListener.yaml
- save-configuration.Task.yaml
- git-credentials.Secret.yaml
- production-repository.ConfigMap.yaml